config/routes.rb
Rails.application.routes.draw do
   resources :articles
  # resources :articles, only: [:show , :index , :new , :create]
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup' , to: 'users#new'
  resources :users , except:[:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true , length: {minimum: 6 , maximum: 100}
    validates :description, presence: true , length: {minimum: 6 , maximum: 100}

end

app/models/user.rb
class User < ApplicationRecord 
  has_secure_password
  before_save { self.email = email.downcase }

  has_many :articles
validates :username, presence: true ,    uniqueness: { case_sensitive: false },  length: {minimum: 6 , maximum: 100}
VALID_EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true ,    uniqueness: { case_sensitive: false },  length: {minimum: 6 , maximum: 100}, format: {with: VALID_EMAIL_FORMAT}

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :set_article, only: %i[ show edit update destroy ]

  # # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
     @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
         @article = Article.find(params[:id])
  end

#   # POST /articles or /articles.json
  def create

    @article = Article.new(params.require(:article).permit(:title , :description))
    @article.user = User.first
    if @article.save()
flash[:notice] = "Article saved sucessfully"
redirect_to @article
    else 
      render "new"
    end
    # respond_to do |format|
    #   if @article.save
    #     format.html { redirect_to @article, notice: "Article was successfully created." }
    #     format.json { render :show, status: :created, location: @article }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
         @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title , :description))
      
      
flash[:notice] = "Article Update sucessfully"
redirect_to @article

    else 
      render "edit"
    end

    # respond_to do |format|
    #   if @article.update(article_params)
    #     format.html { redirect_to @article, notice: "Article was successfully updated.", status: :see_other }
    #     format.json { render :show, status: :ok, location: @article }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
             @article = Article.find(params[:id])
@article.destroy
redirect_to articles_path
  #   @article.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to articles_path, notice: "Article was successfully destroyed.", status: :see_other }
  #     format.json { head :no_content }
  #   end
  end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_article
#       @article = Article.find(params.expect(:id))
#     end

#     # Only allow a list of trusted parameters through.
#     def article_params
#       params.expect(article: [ :title, :description ])
#     end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home 
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def new 
    @user = User.new
   end
   def create 
      

    @user = User.new(user_param)
   
     @user.save()
flash[:notice] = "Welcome to Alpha Blog. #{@user.username}, you have sucessfully sign up"
redirect_to articles_path

   end 
   def edit 
      @user = User.find(params[:id])
   end 
def update
          @user = User.find(params[:id])
              if User.update(user_param)
               flash[:notice] = "Your account information was successfully updated"
redirect_to articles_path
              else 
               render "edit"
              end

end
private
def user_param 
   params.require(:user).permit(:username , :email , :password)
end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div>
    <strong>Title:</strong>
    <%= article.title %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= article.description %>
  </div>

</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
<%= render "shared/Errormsg" , obj: @article%>
      <%= form_with scope: :article, url: articles_path, class: "shadow p-3 mb-3 bg-info rounded" ,local: true do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" ,placeholder: "Title of article" %>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Create Article", class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>

      <div class="mt-3 text-center">
        <%= link_to "[Back to articles]", articles_path, class: "text-info"  %>
      </div>

    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
<h1 class="text-center mt-4"> Edit Articles</h1>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-10">
<%= render "shared/Errormsg" , obj: @article%>
      <%= form_with scope: :article, url: articles_path, class: "shadow p-3 mb-3 bg-info rounded" ,local: true do |f| %>

        <div class="form-group row mb-3">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row mb-3">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" ,placeholder: "Title of article" %>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Update Article", class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>

      <div class="mt-3 text-center">
        <%= link_to "[Back to articles]", articles_path, class: "text-info"  %>
      </div>

    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Articles</h1>

 <div class="container">
 <% @articles.each do |article| %>
 <div class="row justify-content-md-center" >
      <div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-body rounded">
 <div> <h5 class="card-header fst-italic">by <%= article.user.username if article.user %></h5> </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
 <%= link_to "Veiw", article , class:"btn btn-outline-success" %>

 <%= link_to "Edit", edit_article_path(article),  class:"btn btn-outline-primary"%>
<%= form_with model: article, method: :delete, data: { confirm: "Are you sure?" }, class: "d-inline" do %>
  <%= submit_tag "Delete", class: "btn btn-outline-danger" %>
<% end %> </div>
   <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>  </div>
</div>
</div>
</div>
<%end%>
</div>
</div>

app/views/articles/new.html.erb
<div id="page-content">



<% content_for :title, "New article" %>

<h1 class="text-center mt-4">New Article</h1>

<%= render "form", article: @article %>

<br>



</div>

app/views/articles/show.html.erb
<div id="page-content">
<h1 class="text-center mt-4"> ShowArticles</h1>

 <div class="container">
 <div class="row justify-content-md-center" >
      <div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-body rounded">
 <div> <h5 class="card-header fst-italic">by <%= article.user.username if article.user %></h5> </div>
  <div class="card-body">
    <h5 class="card-title text-success"><%= @article.title %></h5>
    <p class="card-text"><%= @article.description %></p>
 

 <%= link_to "Edit", edit_article_path(@article),  class:"btn btn-outline-primary"%>
<%= form_with model: @article, method: :delete, data: { confirm: "Are you sure?" }, class: "d-inline" do %>
  <%= submit_tag "Delete", class: "btn btn-outline-danger" %>
<% end %> </div>
   <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>  </div>
</div>
</div>
</div>

</div>
</div>

app/views/layouts/_foooter.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy;<%= link_to "MAshroor Husain", "https://mashrurhossain.com", class: "text-white"%></small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  
        <%= link_to "Alpha Blog" , root_path, class:"navbar-brand", id:"logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>   <%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
            <li>          <%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Alpha Blog">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

 <body class="d-flex flex-column min-vh-100">

  <%= render 'layouts/navigation' %>

  <div class="container mt-4 ">
    <% flash.each do |name, msg| %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>

  <!-- MAIN CONTENT -->
  <main class="flex-grow-1">
    <%= yield %>
  </main>

  <%= render 'layouts/foooter' %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron   p-5 mb-4 bg-success text-white rounded-3 text-center ">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple component for calling extra attention to featured content.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%=link_to "Sign UP",signup_path , class: "btn btn-success btn-lg"%>
    </div>
  </div>
</div>

app/views/shared/_Errormsg.html.erb
<div class="container">
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
     <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> from being saved</h4>
   <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  <% end %>
  </div>

app/views/users/_form.html.erb
<div class="container" style="min-height: 80vh;">
   <div class="row justify-content-center align-items-center">
    <div class=" card shadow col-6 p-5">
<h2 class="mb-5">Edit User Profile</h2>

<%= form_with(model: @user, local: true) do |f| %>
    <div class="row mb-3">
          <%= f.label :username, class: "col-2 col-form-label" %>
    <div class="col-sm-10">
            <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
  <%= f.label :email, class: "col-2 col-form-label" %>
    <div class="col-sm-10">
       <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
        <%= f.label :password, class: "col-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control", placeholder: "Leave blank to keep current password" %>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Update User</button>
<%end%>
</div>
</div>
</div>

app/views/users/edit.html.erb
<div style = "margin-top : 80px" > 
<%= render "form"%>
<div>

app/views/users/new.html.erb
<%= render 'shared/Errormsg', obj: @user %>

<div class="container d-flex align-items-center justify-content-center" style="min-height: 80vh;">
   <div class="col-md-6 col-lg-5">
  <div class="card shadow p-5" style="width: 100%; max-width: 400px; min-height: 500px;">
<h1 class="text-center mb-4">Sign Up</h1>

<%= form_with model: @user, local: true do |f| %>
  <div class="mb-4">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
  </div>

  <div class="mb-4">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="mb-4">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>


<div class = "mt-5">
  <%= f.submit "Sign Up", class: " btn btn-primary w-100" %></div>
<% end %>
</div>
</div>
</div>